# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Victron Energy Influx Loader add-on
version: "1.0.0"
slug: example
description: Victron Energy Influx Loader
url: "https://github.com/rkemendi/tree/main/victron-grafana"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "victronenergy/venus-influx-loader"
